In [1]:
import pandas as pd
import tensorflow as tf

In [4]:
string = tf.Variable('This is a string',tf.string)
number = tf.Variable(324,tf.int16) # the most common type
floating = tf.Variable(3.14,tf.float64)
# scaler value > one value only
# vector > more values

In [10]:
# Rank/Dregree > number of dimensions involved in a tensor
rank1_tensor = tf.Variable(["Test","ok","bye"],tf.string) # arrays are always at least rank 1
rank2_tensor = tf.Variable([['Test','ok','bye'],['Test','ok','bye']],tf.string)

In [11]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
# Shape
# numbe rof items in each dimension
rank2_tensor.shape

TensorShape([2, 3])

In [13]:
rank1_tensor.shape

TensorShape([3])

In [23]:
# Changing Shape
# ex. throwing all 6 elements in rank2 into a rank1
reshaped_tensor = tf.reshape(rank2_tensor,[6])
print(reshaped_tensor)
# or
reshaped_tensor = tf.reshape(rank1_tensor,[3,-1]) # same as [3,1]
print(reshaped_tensor)

tf.Tensor([b'Test' b'ok' b'bye' b'Test' b'ok' b'bye'], shape=(6,), dtype=string)
tf.Tensor(
[[b'Test']
 [b'ok']
 [b'bye']], shape=(3, 1), dtype=string)


In [ ]:
'''Types of tensors:
Variable
Constant
Placeholde
SparseTensor
'''

In [24]:
tf.ones([5,5,5,5])

<tf.Tensor: shape=(5, 5, 5, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

  